### ISSUE TITLE
Add extension to Open VSX Registry

### ISSUE THREAD

**Issue by jharmer95** [standard/vscode-standard#111]
**What version of this package are you using?**
N/A

**What problem do you want to solve?**
StandardJS is only available on the Microsoft VSCode Marketplace. This prevents it from being used by open-source versions of VSCode (i.e. VSCodium, Theia).

**What do you think is the correct solution to this problem?**
Also publish the extension to [Open VSX](https://open-vsx.org), guide available [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

**Are you willing to submit a pull request to implement this change?**
N/A

**Comment by EchedelleLR** [comment]
I am interested too

**Comment by EchedelleLR** [comment]
As pointed by other users who requested it for their favourite extensions "It is unclear if it's legal to use the official Microsoft extension marketplace on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168)" so would be more beneficial in general to have it on Open VSX.

**Comment by theoludwig** [comment]
Apparently, the extension is published to Open VSX Registry by @markwylde
Link : https://open-vsx.org/extension/markwylde/vscode-standardjs

**Comment by markwylde** [comment]
> Apparently, the extension is published to Open VSX Registry by @markwylde
> Link : https://open-vsx.org/extension/markwylde/vscode-standardjs

Yeah Divlo, I have published it temporarily, but would love to delete it in favour of an official one from the standard team.

**Comment by markwylde** [comment]
Updated to [1.4.0](https://open-vsx.org/extension/markwylde/vscode-standardjs)

Let me know if there's any problems.

**Comment by feross** [comment]
Cool, happy to publish an official version to Open VSX if it's not too much extra work. It looks like they're changing the publishing process in December 2020 so I want to wait until that's finished before figuring out the process. https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by markwylde** [comment]
@feross openvsx has now been transferred to eclipse and the new process is in effect. I've just gone through the pairing process, and it worked.

So if you do have a few minutes free one day, you should be able to register and publish the extension. If you need any help, please feel free to reach out.

Make sure to "claim" [[1]](https://github.com/EclipseFdn/open-vsx.org#claiming-namespace-ownership) the standard namespace, so no one else can publish under the name "standard".

Also once it's published, I'll remove the version I've uploaded to avoid any confusion.

1. https://github.com/EclipseFdn/open-vsx.org#claiming-namespace-ownership

**Comment by theoludwig** [comment]
I guess, we could have some Continuous Deployment (CD) for automatically publishing to the 2 marketplaces automatically when we create a new release ("tag") on GitHub.

Also the branch on `master` isn't working for `standard` engine since #140, because the changes were indeed working for `standard` but it wasn't for `ts-standard` that needed a `tsconfig.json` file to work, so I tried a workaround in #139, and add a small condition to only do the thing with `standard` engine, but it seems like it brokes everything (my bad).
So in the #142 PR, I revert the #140 PR and now everything is working as expected for every engines but obviously, we don't solve the #140 PR.

We could first merge #142, and then release `v1.5.0` on both marketplace. :+1: 

**EDIT:** in #142 PR, I implemented automated deployment to deploy to both *VSCode Marketplace* and *Open VSX* automatically.

**Comment by jharmer95** [comment]
Awesome, thanks!

**Comment by theoludwig** [comment]
Thanks for your help! @markwylde 
Could you please, remove your version of the extension to `open-vsx` registry, thanks!
The extension is now available here: https://open-vsx.org/extension/standard/vscode-standard

**Comment by markwylde** [comment]
I've requested the removal now. Thanks @Divlo
