### ISSUE TITLE
standard.workingDirectories doesn't work

### ISSUE THREAD

**Issue by andyyxw** [standard/vscode-standard#118]
**What version of this package are you using?**
`standard 14.3.4`
**What operating system, Node.js, and npm version?**
`macOS 10.14.6`, `node 14.3.0`, `npm 6.14.5`
**What happened?**
I set `"standard.workingDirectories": ["/Users/andy/workspace/myProject"]` in vscode `settings.json`, but `standard` still works in all `.js` files, seems a bug.
**What did you expect to happen?**
standard.workingDirectories  works fine, or other solutions.
**Are you willing to submit a pull request to fix this bug?**

**Comment by yelwinsoe** [comment]
I've tested and debug this, it happens when the "standard.workingDirectories" path are under the workspace itself and standard for workspace is enable. @andyyxw may be this was your setup?

Should we ignore the workspace setting if there are values in the "standard.workingDirectories"?
@Divlo @feross i can help fix that if this is what we want to do?

**Comment by yelwinsoe** [comment]
I've tested this and I think i might be able to help fix it but i need some help.
One question i have is, r we going to ignore the workspace and global config if there's 'standard.workingDirectories' in the settings.json?
