### ISSUE TITLE
Node.js Buffer() is deprecated.

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [standard/vscode-standard#124]
**What version of this package are you using?** 1.3.0

**What operating system, Node.js, and npm version?** Windows, Node 14.10.1, Npm 6.14.8

**What happened?** The extension output has this error message:
```
(node:4704) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**What did you expect to happen?** I expected the code to not use `Buffer()`, because it's deprecated.

**Are you willing to submit a pull request to fix this bug?** Yes

**Comment by dziku86** [comment]
**What version of this package are you using?** 1.3.0
**What operating system, Node.js, and npm version?** Windows 7 32 bit, Node 12.14.1, Npm 6.9.0
**VSC version** 1.51.0-insider
Same error but on `(node:3760)` after installing latest standard 16.0.0
After typing anything I get this error:
`The "path" argument must be of type string. Received type object`

I think the issue lies in one of the previous VSC updates. I can't rollback because on the VSC site there are only 64 bit Win archived versions. Yes I'm still on 32bit.

**EDIT:**
I got it to work on: 
**Node v9.11.2:** last version that allows to use new Buffer() and Buffer() outside of the node_modules directory;
**standard@9.0.2:** last version that allows to use deprecated Node.js APIs (`Buffer()`).
plus
**standard-engine@14.0.1:** to solve this bug [https://github.com/standard/standard/issues/1584](https://github.com/standard/standard/issues/1584)

Though I'm still getting deprecation warning about `Buffer()`.

**Comment by feross** [comment]
@dziku86 Yep, your issue was related to https://github.com/standard/standard/issues/1584. Thanks for updating your comment! I will collapse your comment to avoid confusion for this issue.
