### ISSUE TITLE
Looking for a maintainer!

### ISSUE THREAD

**Issue by feross** [standard/vscode-standard#131]
We're looking for a new maintainer or two to help with this repo. This extension has 300k+ users on VSCode – your work will have a huge impact!

Good first issues:

- Update TypeScript to the latest version https://github.com/standard/vscode-standardjs/issues/130
- Test out this PR and confirm it works: https://github.com/standard/vscode-standardjs/pull/126
- Go through the open issues and send PRs for any that look easy to fix
- Go through the open issues and comment "This issue should be closed" for the issues that are invalid/already fixed/duplicate, etc.

**Comment by theoludwig** [comment]
This extension for `standard` is awesome, but the codebase is old and outdated and also don't have automated tests.
I consider to clean up those things, see  #132. Feel free to tell me if what I plan to do is wrong or right.

**Comment by feross** [comment]
@Divlo Excellent work! Just left a comment on your PR.

**Comment by theoludwig** [comment]
Now that we have linting rules and updated dependencies, here are the tasks we could consider to do by oder of priority (tell me if you don't agree with something) : 
- [x] Update README.md (maybe with badges like travis build passing, ts-standard etc)
- [x] Update LICENSE to have a "official" MIT License, currently we have a MIT LICENSE from the `vscode-eslint` fork, but it is not recognized by github as a LICENSE (tell me if I'm wrong and if we can't do that because of legal advice)
- [x] Add dependabot as it is the case in the [standard](https://github.com/standard/standard) repo since https://github.com/standard/standard/pull/1582
- [x] Add automated tests #44 
- [ ] Refactor code to avoid having file with 1500 lines of code, better split it in many smaller files (since we will have automated tests before doing this, we can do this in a safer way)

I guess that's a good starting point, if you think, you know how to do one of these tasks, feel free to open PRs. :+1: 

Also @feross, could you put the link of the extension on the vscode marketplace in the website section in github ?
https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs

**Comment by feross** [comment]
These all sound like good ideas! Feel free to tackle them in whatever order you prefer. I'm happy to review your PRs, and I think you can also tag others like @toddbluhm and @LinusU for TypeScript-specific reviews :)

> Also @feross, could you put the link of the extension on the vscode marketplace in the website section in github ?
marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs

Done!

**Comment by feross** [comment]
Another good task would be go through the existing issues and try to triage them. I think there's lots of invalid issues and questions that can probably be closed.

**Comment by theoludwig** [comment]
Right, I answer and closed incorrect issues. If I accidentally closed a real issue, please reopen it.
Also I add labels to issues.

**Comment by feross** [comment]
@Divlo Thank you! I just looked over all the issues you closed. Looks good to me!
