### ISSUE TITLE
Can I make it a little bit less strict by using options?

### ISSUE THREAD

**Issue by fedorinoGore** [standard/vscode-standard#7]
I want to switch some of the errors to warnings:
For example, I'm trying to do something like this, and it is not working:
```json
"standard.options": {
        "rules": {
            "no-unused-vars": "warn"
        } 
    }
```

**Comment by chenxsan** [comment]
No, You can't. Please check it [here](http://standardjs.com/#can-you-make-rule-x-configurable).

**Comment by denizdogan** [comment]
You can't change anything about JavaScript Standard Style, that would kind of defeat the purpose, but it *is* possible to change the parser that `standard` uses internally to something else, so that you can use decorators and other things that aren't necessarily part of the Standard style.

https://github.com/feross/standard/issues/106#issuecomment-106883572

This allows you to use decorators and other things not understood by `standard` by default. I don't think this extension will support it though.
