### ISSUE TITLE
undefined is not validating any files yet

### ISSUE THREAD

**Issue by eetee** [standard/vscode-standard#76]
- StandardJS version? 12.0.1
- VSCode version? 1.29.1
- StandardJS configuration?

```javascript
  "standard": {
    "parser": "typescript-eslint-parser",
    "plugins": [
      "typescript"
    ],
    "env": [
      "jest"
    ]
  }
```
- What do you have in the `OUTPUT` panel?

Can't open:
![image](https://user-images.githubusercontent.com/3005702/49703598-c022b380-fc6b-11e8-90e8-f9365f98f97b.png)

---
Can't get the extension to work. Regular standardjs CLI works fine.
I've tried local devDependencies settings and also replicating this using global install

**Comment by chenxsan** [comment]
It would be helpful if you can set up a simple repository on github that I can test.

**Comment by eetee** [comment]
Hi @chenxsan 

Thanks for looking at this.

Reproduction:
1. Clone eetee/vscode-standardjs-76
2. npm install (dev dependencies - standard typescript-eslint-parser eslint-plugin-typescript)
3. Open test.ts in vscode
4. vscode command: Javascript Standard Style: Show Output Channel

Behaviour: no output channel created, vscode notifies "undefined is not validating any files yet"

This is my config for vscode:
```json
{
    "breadcrumbs.enabled": true,
    "editor.lineNumbers": "relative",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "standard.autoFixOnSave": true,
    "standard.usePackageJson": true,
    "javascript.validate.enable": false,
    "typescript.validate.enable": false
}
```

**Comment by eetee** [comment]
If it helps:
![image](https://user-images.githubusercontent.com/3005702/49705114-a5a70500-fc80-11e8-8cf7-681d3a96ab24.png)

**Comment by joshuaquek** [comment]
For me the fix was to add this to my vscode settings file:

```javascript
...
...
"standard.options": {
    "parser": "typescript-eslint-parser",
    "plugins": [
      "typescript"
    ]
},
"files.associations": {
  "*.js": "javascript",
  "*.ts": "javascript"
},
...
...
```

Then in your project:
```
npm i standard babel-eslint eslint-plugin-typescript typescript-eslint-parser --save-dev
```

After that it just worked.

**Comment by CherryDT** [comment]
Seems this issue came back. I remember `standard` had no issue with my repository in the past, but this time it does show exactly this error. It's _not_ TypeScript though! What do you need to debug this?

**Comment by falco467** [comment]
I have the same error - only JavaScript files and the old StandardJS Extension is working without problems, the new one gives this error.

**Comment by sryze** [comment]
Same problem with VS Code 1.63.2

Update:

Installing the `standard` package locally inside my project fixed this ^ issue

**Comment by falco467** [comment]
I feel a little stupid, but I had to explicitly enable the Setting: "standard.enableGlobally": true to get rid of this error.
This setting was not needed in the older version and I did not find any explicit notification for me to enable this. I also think it is not very useful, since extensions can be enabled via the settings for every workspace.

I think this setting should disappear altogether - or at least default to true. - If I install an extension and explicitly enable it for my workspace via the extension manager, I expect it to be active and work. And not having to enable an additional setting for the extension to actually work.

**Comment by theoludwig** [comment]
@falco467 The extension will automatically be enabled in projects that has one of the engines installed in `devDependencies` in `package.json` as stated in README.

We don't recommend using `"standard.enableGlobally": true` option.

The idea is that you might work on projects using Standard and others with ESLint with completely different rules, so to don't conflict, we enable by default when it makes more sense, when we think you actually use Standard in your project.

Hopefully it is clearer, don't hesitate to open new issues if you have other questions or problems. :smile:

**Comment by falco467** [comment]
Thank you for this information. The standard way for most extensions is the option to enable/disable the extension via workspace settings. So for example my SCSS extension is disabled globally (extension manager) and enabled in the workspaces I need it. This has the added benefit of the extension not even being loaded, when it is not used.
Although your option provides some nice magic for some use-cases, it also confuses some users, since it behaves different than the default way of enabling/disabling an extension via the extension manager.
Most of my JS-Projects don't use npm at all, so standard never enables automatically.
